name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4.1.1

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-35-179-90-244.eu-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: krahristov
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t krahristov/portfolio-frontend:latest .
          docker push krahristov/portfolio-frontend:latest

      - name: Copy deployment script

        run: |
          scp -o StrictHostKeyChecking=no Scripts/deploy_script_portfolio_frontend.sh ubuntu@ec2-35-179-90-244.eu-west-2.compute.amazonaws.com:~

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-35-179-90-244.eu-west-2.compute.amazonaws.com "\
          ls -l ~/deploy_script_portfolio_frontend.sh && \
          chmod +x ~/deploy_script_portfolio_frontend.sh && \
          bash ~/deploy_script_portfolio_frontend.sh"